package com.stm.data.entity;
// Generated Jul 31, 2017 10:22:15 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Service generated by hbm2java
 */
@Entity
@Table(name = "service", catalog = "stm")
public class Service {

	private long id;
	private String name;
	private String path;
	private Set<Page> pages = new HashSet<Page>(0);
	private Set<GroupHasService> groupHasServices = new HashSet<GroupHasService>(0);

	public Service() {
	}

	public Service(String name, String path, Set<Page> pages, Set<GroupHasService> groupHasServices) {
		this.name = name;
		this.path = path;
		this.pages = pages;
		this.groupHasServices = groupHasServices;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "path", length = 45)
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "service")
	public Set<Page> getPages() {
		return this.pages;
	}

	public void setPages(Set<Page> pages) {
		this.pages = pages;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "service")
	public Set<GroupHasService> getGroupHasServices() {
		return this.groupHasServices;
	}

	public void setGroupHasServices(Set<GroupHasService> groupHasServices) {
		this.groupHasServices = groupHasServices;
	}

}
