package com.stm.data.entity;
// Generated Jul 31, 2017 10:22:15 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Track generated by hbm2java
 */
@Entity
@Table(name = "track", catalog = "stm")
public class Track {

	private long id;
	private Contract contract;
	private Warehouse warehouseByWarehouseTo;
	private Warehouse warehouseByWarehouseFrom;
	private String description;
	private BigDecimal startingPrice;
	private Set<Shipment> shipments = new HashSet<Shipment>(0);
	private Set<PriceList> priceLists = new HashSet<PriceList>(0);

	public Track() {
	}

	public Track(Contract contract, Warehouse warehouseByWarehouseTo, Warehouse warehouseByWarehouseFrom,
			String description, BigDecimal startingPrice, Set<Shipment> shipments, Set<PriceList> priceLists) {
		this.contract = contract;
		this.warehouseByWarehouseTo = warehouseByWarehouseTo;
		this.warehouseByWarehouseFrom = warehouseByWarehouseFrom;
		this.description = description;
		this.startingPrice = startingPrice;
		this.shipments = shipments;
		this.priceLists = priceLists;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "contract_id")
	public Contract getContract() {
		return this.contract;
	}

	public void setContract(Contract contract) {
		this.contract = contract;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "warehouse_to")
	public Warehouse getWarehouseByWarehouseTo() {
		return this.warehouseByWarehouseTo;
	}

	public void setWarehouseByWarehouseTo(Warehouse warehouseByWarehouseTo) {
		this.warehouseByWarehouseTo = warehouseByWarehouseTo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "warehouse_from")
	public Warehouse getWarehouseByWarehouseFrom() {
		return this.warehouseByWarehouseFrom;
	}

	public void setWarehouseByWarehouseFrom(Warehouse warehouseByWarehouseFrom) {
		this.warehouseByWarehouseFrom = warehouseByWarehouseFrom;
	}

	@Column(name = "description", length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "starting_price", scale = 3)
	public BigDecimal getStartingPrice() {
		return this.startingPrice;
	}

	public void setStartingPrice(BigDecimal startingPrice) {
		this.startingPrice = startingPrice;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "track")
	public Set<Shipment> getShipments() {
		return this.shipments;
	}

	public void setShipments(Set<Shipment> shipments) {
		this.shipments = shipments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "track")
	public Set<PriceList> getPriceLists() {
		return this.priceLists;
	}

	public void setPriceLists(Set<PriceList> priceLists) {
		this.priceLists = priceLists;
	}

}
