package com.stm.data.entity;
// Generated Jul 31, 2017 10:22:15 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Warehouse generated by hbm2java
 */
@Entity
@Table(name = "warehouse", catalog = "stm")
public class Warehouse {

	private long id;
	private String city;
	private BigDecimal capacity;
	private String managerEmail;
	private String phoneNumber;
	private String description;
	private Set<Track> tracksForWarehouseTo = new HashSet<Track>(0);
	private Set<Track> tracksForWarehouseFrom = new HashSet<Track>(0);

	public Warehouse() {
	}

	public Warehouse(String city, BigDecimal capacity, String managerEmail, String phoneNumber, String description,
			Set<Track> tracksForWarehouseTo, Set<Track> tracksForWarehouseFrom) {
		this.city = city;
		this.capacity = capacity;
		this.managerEmail = managerEmail;
		this.phoneNumber = phoneNumber;
		this.description = description;
		this.tracksForWarehouseTo = tracksForWarehouseTo;
		this.tracksForWarehouseFrom = tracksForWarehouseFrom;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "city", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "capacity", scale = 3)
	public BigDecimal getCapacity() {
		return this.capacity;
	}

	public void setCapacity(BigDecimal capacity) {
		this.capacity = capacity;
	}

	@Column(name = "manager_email", length = 100)
	public String getManagerEmail() {
		return this.managerEmail;
	}

	public void setManagerEmail(String managerEmail) {
		this.managerEmail = managerEmail;
	}

	@Column(name = "phone_number", length = 12)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "description", length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "warehouseByWarehouseTo")
	public Set<Track> getTracksForWarehouseTo() {
		return this.tracksForWarehouseTo;
	}

	public void setTracksForWarehouseTo(Set<Track> tracksForWarehouseTo) {
		this.tracksForWarehouseTo = tracksForWarehouseTo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "warehouseByWarehouseFrom")
	public Set<Track> getTracksForWarehouseFrom() {
		return this.tracksForWarehouseFrom;
	}

	public void setTracksForWarehouseFrom(Set<Track> tracksForWarehouseFrom) {
		this.tracksForWarehouseFrom = tracksForWarehouseFrom;
	}

}
